# Generated by Django 5.0.4 on 2024-09-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_is_checked_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('LAB', 'Exame de Laboratorio'), ('IMG', 'Exame de Imagem'), ('CRD', 'Exame Cardiologico')], default='LAB', max_length=3),
        ),
    ]
